"""LLM-backed summarizer that returns a structured 4-part summary and renders
it to Zotero-friendly note HTML."""

from __future__ import annotations

import html
from typing import List

from langchain_core.prompts import ChatPromptTemplate
from pydantic import BaseModel, Field


class PaperSummary(BaseModel):
    """The structured summary the model is asked to produce."""

    motivation: str = Field(
        description="The motivation and the main problem the paper sets out to solve."
    )
    key_findings: List[str] = Field(
        description="The most important findings / contributions, as concise bullet points."
    )
    methodology: str = Field(
        description="The methodology, approach, data, or experimental setup used."
    )
    future_work: str = Field(
        description="Future work, limitations, and open directions the paper suggests."
    )


_SYSTEM = (
    "You are a meticulous research assistant. You read academic papers and "
    "produce faithful, concise summaries grounded strictly in the provided text. "
    "Do not invent results. If a section's information is missing from the text, "
    "say so briefly rather than guessing."
)

_PROMPT = ChatPromptTemplate.from_messages(
    [
        ("system", _SYSTEM),
        (
            "human",
            "Summarize the following paper.\n\n"
            "Title: {title}\n"
            "Authors: {authors}\n\n"
            "--- PAPER TEXT (may be truncated) ---\n{text}\n--- END ---",
        ),
    ]
)


class Summarizer:
    def __init__(self, llm, model_label: str):
        self.model_label = model_label
        self.chain = _PROMPT | llm.with_structured_output(PaperSummary)

    def summarize(self, title: str, authors: str, text: str) -> PaperSummary:
        return self.chain.invoke({"title": title, "authors": authors, "text": text})


def _para(text: str) -> str:
    """Escape text and preserve line breaks for HTML notes."""
    return html.escape(text).replace("\n", "<br/>")


def summary_to_html(title: str, summary: PaperSummary, model_label: str) -> str:
    """Render a PaperSummary as a Zotero note (HTML). Contains SUMMARY_MARKER
    via the footer string so re-runs can detect it."""
    findings = "".join(f"<li>{_para(f)}</li>" for f in summary.key_findings)
    if not findings:
        findings = "<li>—</li>"

    return (
        '<div data-schema-version="9">'
        "<h1>🤖 AI Summary</h1>"
        f"<p><strong>{html.escape(title)}</strong></p>"
        "<h2>Motivation &amp; Main Problem</h2>"
        f"<p>{_para(summary.motivation)}</p>"
        "<h2>Key Findings</h2>"
        f"<ul>{findings}</ul>"
        "<h2>Methodology</h2>"
        f"<p>{_para(summary.methodology)}</p>"
        "<h2>Future Work</h2>"
        f"<p>{_para(summary.future_work)}</p>"
        f"<p><em>Generated by zotery using {html.escape(model_label)}.</em></p>"
        "</div>"
    )


def preview(summary: PaperSummary) -> str:
    """Plain-text preview for --dry-run output."""
    findings = "\n".join(f"    - {f}" for f in summary.key_findings)
    return (
        "  Motivation & Problem:\n"
        f"    {summary.motivation}\n"
        "  Key Findings:\n"
        f"{findings}\n"
        "  Methodology:\n"
        f"    {summary.methodology}\n"
        "  Future Work:\n"
        f"    {summary.future_work}"
    )
